name: Build flatpak

# ⚠️ Will build the version published to flathub, not the latest commit
on:
  workflow_dispatch:
  workflow_call:
#   push:
#     tags:
#       - '*'
#     branches: [master]
#   pull_request:
#     branches: [master]

jobs:
  flatpak:
    name: Build Flatpak
    runs-on: ubuntu-latest
    container:
      image: bilelmoussaoui/flatpak-github-actions:gnome-44
      options: --privileged
    steps:
      - uses: actions/checkout@v3
        with:
          repository: flathub/io.github.vemonet.EmojiMart
          path: './'

      - uses: flatpak/flatpak-github-actions/flatpak-builder@v6.1
        with:
          bundle: EmojiMart.flatpak
          manifest-path: io.github.vemonet.EmojiMart
          cache-key: flatpak-builder-${{ github.sha }}
